### ISSUE TITLE
Change language of the thesis

### ISSUE THREAD

**Issue by ge69led** [TUM-Dev/tum-thesis-latex#19]
Hello, i want to use the template for my german thesis and wanted to ask if there is any easy way i have overseen to change its language to german, so that the cover page is in german for example. Or so that it says "Literaturverzeichnis" instead of "Bibliography". I also do not know if this is the right way to ask something like this, if not i am sorry.

**Comment by COM8** [comment]
@ge69led  welcome and yes, this is the correct place to ask such questions. This template is intended for English first thesis. But you can change a lot of the automatic translations by following this example:
https://de.overleaf.com/learn/latex/German

Besides that, stuff like `School of [...]` needs to be translated by you.
