### ISSUE TITLE
Including the degree course in the cover/ title

### ISSUE THREAD

**Issue by juli4p** [TUM-Dev/tum-thesis-latex#8]
Hello,

thanks for the great template!

I noticed that it uses getFaculty() for both the faculty and the course of degree in the cover/ title. Im studying Information Systems so my cover should say: 
SCHOOL OF COMPUTATION, INFORMATION AND TECHNOLOGY — INFORMATICS (faculty)
Bachelor’s Thesis in Information Systems (course of degree)

But currently I can only specify the faculty and it is used for both lines. So my suggestion would be to add a \newcommand*{\getDegree} in main and use getDegree() instead of getFaculty() in line 25/ 17 of cover/ title. 
Alternatively since the template is meant for the Informatics faculty you could set it to Informatics by exchanging getFaculty() with "Informatics" in line 19/ 11 of cover/ title and only use the command for the degree.

Best regards,
Julian

**Comment by COM8** [comment]
Thanks for reporting and I agree!

Would you like to create a PR for it?

**Comment by juli4p** [comment]
Sure, I'll do that.
